name: Publish

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: tugrulates/blog-code
          ref: staging
          token: ${{ secrets.PUBLISH_TOKEN }}
      - run: |
          git submodule update --init --recursive --remote docs
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add --all
          git commit -m "Update docs" || echo "No changes to commit"
          git push
