name: Doc publish

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with: 
          repository: tugrulates/tugrulates.github.io
          token: ${{ secrets.PUBLISH_TOKEN }}

      - name: Pull & update submodules recursively
        run: git submodule update --init --recursive --remote docs
      - name: Commit
        run: |
          git config user.email "${{ secrets.PUBLISH_EMAIL }}"
          git config user.name "${{ secrets.PUBLISH_NAME }} [bot]"
          git add --all
          git commit -m "Update docs" || echo "No changes to commit"
          git push
