name: Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger publish
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.dispatches.createDispatchEvent({
              owner: "tugrulates",
              repo: "blog-code",
              event_type: "Publish",
            })
